name = "zzz-pull-planner-scraper"
main = "src/worker/index.ts"
compatibility_date = "2025-01-01"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "zzz-pull-planner"
database_id = "7fafd514-2b33-48e0-ae42-7e58e14b770a"

[[r2_buckets]]
binding = "ASSETS_BUCKET"
bucket_name = "zzz-assets"
preview_bucket_name = "zzz-assets"

[triggers]
crons = [ "0 4 * * *" ]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
